name: PR Checklist

on:
  pull_request:
    types: [opened]

jobs:
  add-checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Comment PR with checklist
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for submitting your PR. The PR states are Tech review -> Doc review -> Editorial review -> Merged.
            
            ### PR checklist
            - [ ] Tech review: 
              - If you're a developer submitting documentation for a feature you implemented, you can skip this step.
              - If you need help finding a tech reviewer, tag @kolchfa-aws.
            - [ ] **Once the PR is ready for doc review, tag the assignee of this PR or @kolchfa-aws.**
            - [ ] Doc review: A doc reviewer may:
              - Leave comments/suggestions: You will implement comments and add suggestions to batch and commit the batch as one commit.
              - Edit the PR: The doc reviewer will push edits to this PR directly (let us know if you don't want this option).
            - [ ] Editorial review: The doc reviewer will put the PR through editorial review.

            Please be available to answer questions. Thank you!

      - name: Auto assign PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.payload.pull_request.user.login]
            })
